// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Drivers = sequelize.define('driversTable', {
    email: {
      type: DataTypes.STRING,
    },
    phone: {
      type: DataTypes.STRING,
    },
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    drivingLicence: {
      type: DataTypes.STRING,
    },
    criminalRecord: {
      type: DataTypes.STRING,
    },
    insuranceCertificate: {
      type: DataTypes.STRING,
    },
    onboardingStatus: {
      type: DataTypes.STRING,
      defaultValue: "signed up",
    },
    carModel: {
      type: DataTypes.STRING,
    },
    bookingStatus: {
      type: DataTypes.STRING,
    },
    carPicture: {
      type: DataTypes.STRING,
    },
    profilePicture: {
      type: DataTypes.STRING,
    },
    location: {
      type: DataTypes.ARRAY(DataTypes.FLOAT),
    },
  }, {
    tableName: 'drivers',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Drivers.associate = (models) => {
    Drivers.hasMany(models.drives, {
      foreignKey: {
        name: 'driverIdKey',
        field: 'driver_id',
      },
      as: 'drives',
    });
  };

  return Drivers;
};
