// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Issues = sequelize.define('issues', {
    reason: {
      type: DataTypes.STRING,
    },
    priorityStatus: {
      type: DataTypes.STRING,
    },
    manager: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'issues',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Issues.associate = (models) => {
    Issues.belongsTo(models.drives, {
      foreignKey: {
        name: 'driveIdKey',
        field: 'drive_id',
      },
      as: 'drive',
    });
  };

  return Issues;
};
